/*******************************************************************************************************
  Impact of COVID-19 on cancer screening and treatment in older adults: The Multiethnic Cohort Study
  10/2023
********************************************************************************************************/

label 
/*Variables from MEC Baseline Questionnaire 1993-1996*/
MEC_Baseline_CORR_SEX="Preferred Sex Variable (1=Male, 2=Female)"
MEC_Baseline_ETH="Ethnicity (B,H,L,J,W,O) (B=Black, H=Hawaiian, L=Latino, J=Japanese, W=White, O=Other)"
MEC_Baseline_yrsschl_c="Maximum years of education attained, Continuous,(Participant Written Response)"
MEC_Baseline_packyrs="Smoking Pack Years from MEC QX 1, (Participant Written Response)"
MEC_Baseline_ethanol="Alcohol (grams per day), (Participant Written Response)"
MEC_Baseline_DP_HEI2010_totscore="Dietary Patterns Healthy Eating Index-2010 score (calculated from HEI components)"
MEC_Baseline_newqi_corr2="Body Mass Index (kg/m^2) at MEC Baseline"

/*Variables derived for MEC COVID Analysis*/
Education="Educational Level
	('1=Did Not Complete 6th Grade', '2=6th-8th Grade') then Education='<= 8yrs';
	('3=9th-10th Grade', '4=11th-12th Grade') then Education='9-12 yrs';
	('5=Vocational School' then Education='Vocational';
	('6=Some College', '7=Graduated College', '8=Graduate or Professional School') then Education='At Least Some College'"
age_survey="Age at time of survey response"
age_survey_group="Age stratified into proportional groups"
cv19_b_bmi= "BMI (kg/m^2)"
cv19_b_q92_ent="PostponeProvider-ENT (1=yes, NULL=not)"
cv19_b_q92_allerg="PostponeProvider-Allergist (1=yes, NULL=not)"
cv19_b_q92_audio="PostponeProvider-Audiologist (1=yes, NULL=not)"
cv19_b_q92_gyn="PostponeProvider-OB-GYN (1=yes, NULL=not)"
cv19_b_q92_derm="PostponeProvider-Dermatology (1=yes, NULL=not)"
cv19_b_q92_dent="PostponeProvider-Dentist (1=yes, NULL=not)"
cv19_b_q92_eye="PostponeProvider-Eye (1=yes, NULL=not)"
cv19_b_q92_gastro="PostponeProvider-Gastroenterologist (1=yes, NULL=not)"
cv19_b_q92_lab="PostponeProvider-Laboratory Testing/Imaging (1=yes, NULL=not)"
cv19_b_q92_therapy="PostponeProvider-Physical/Massage/Chiropractic Therapy (1=yes, NULL=not)"
cv19_b_q92_ortho="PostponeProvider-Orthopedist (1=yes, NULL=not)"
cv19_b_q92_podi="PostponeProvider-Podiatrist (1=yes, NULL=not)"
cv19_b_q92_onco="PostponeProvider-Oncologist (combined written and MultiSelectQx responses) (1=yes, NULL=not)"
cv19_b_q92_PCP="PostponeProvider-Primary care physician (combined written and MultiSelectQx responses)(1=yes, NULL=not)"
cv19_b_q92_urol="PostponeProvider-Urologist (1=yes, NULL=not)"
cv19_b_q92_neuro="PostponeProvider-Neurologist (1=yes, NULL=not)"
cv19_b_q92_rheuma="PostponeProvider-Rheumatologist (1=yes, NULL=not)"
cv19_b_q92_pulm="PostponeProvider-Pulmonologist (1=yes, NULL=not)"
cv19_b_q92_cardio="PostponeProvider-Cardiologist (combined written and MultiSelectQx responses)(1=yes, NULL=not)"
cv19_b_q96_imaging="PostponeScreeningType-Imaging (e.g., CAT scan, DEXA, MRI) (1=yes, NULL=not)"
cv19_b_q96_cervical="PostponeScreeningType-Cervical cancer screening (e.g., PAP smear, pelvic exam)(1=yes, NULL=not)"

/*Variables from MEC COVID Questionnaire*/
CV19_B_Q4_ht="Height (inches)"  
CV19_B_Q5_wt="Weight (pounds)" 
cv19_b_q7="ILive... (1=by self, 2=spouse, 3=relatives, 4=retirement/care home, 5=other)" 
cv19_b_q8="Type of Dwelling (1=detached, 2=town house, 3=low rise, 4=high rise, 5=other)" 
cv19_b_q8TEXT="Dwelling Type-Other Specify (Participant Written Response)" 
cv19_b_q10="Health Problems Require Staying Home (Y=Yes, N=No)" 
cv19_b_q11="Living Assistance (Y=Yes, N=No)" 
cv19_b_q12="Someone To Count On (Y=Yes, N=No)" 
cv19_b_q13="Using Walking Aid (Y=Yes, N=No)" 
cv19_b_q14="Have Health Problems Limiting Activity (Y=Yes, N=No)" 
cv19_b_q15="Have Heart Disease (Y=Yes, N=No)" 
cv19_b_q16="Have Hypertension (Y=Yes, N=No)" 
cv19_b_q17="Have Diabetes (Y=Yes, N=No)" 
cv19_b_q18="Have Lung Disease (Y=Yes, N=No)" 
cv19_b_q19="Smoking (1=Never, 2=Not currently, but in the past, 3=Yes)"
cv19_b_q20="Years Since Last Smoked (If Q19=2)" 
cv19_b_q21="Have Kidney Disease (Y=Yes, N=No)" 
cv19_b_q22="Cancer Diagnosis in Past 5 Years (Y=Yes, N=No)" 
cv19_b_q23="Had Flu Vaccination (Y=Yes, N=No)" 
cv19_b_q24="Last Flu Vaccination (MM/YYYY, If Q23=Y)" 
cv19_b_q25="Taking Immunosuppressant Medication (Y=Yes, N=No)" 
cv19_b_q26="Taking Pepcid (Y=Yes, N=No)"
cv19_b_q27="Taking Aspirin (Y=Yes, N=No)"
cv19_b_q28="Taking NSAIDs (Y=Yes, N=No)" 
cv19_b_q29="Taking Blood Thinning Medication (Y=Yes, N=No)"
cv19_b_q30="Taking Blood Pressure Medication ending in -Pril (Y=Yes, N=No)"
cv19_b_q31="Taking Blood Pressure Medication ending in -Sartan (Y=Yes, N=No)" 
cv19_b_q32="Made Changes to Lifestyle During COVID Pandemic (Y=Yes, N=No)" 
cv19_b_q33="Lifestyle Change-MultiSelectQx (Select all that apply)"
cv19_b_q33_1="LifestyleChange-Covering Cough/Sneeze (1=yes, NULL=not)" 
cv19_b_q33_2="LifestyleChange-Frequent Handwashing (1=yes, NULL=not)" 
cv19_b_q33_3="LifestyleChange-Handwashing Longer (1=yes, NULL=not)"
cv19_b_q33_4="LifestyleChange-Increased Sanitizer Usage (1=yes, NULL=not)" 
cv19_b_q33_5="LifestyleChange-Frequently Disinfecting Surfaces (1=yes, NULL=not)" 
cv19_b_q33_6="LifestyleChange-Keeping 6Ft Distance (1=yes, NULL=not)"
cv19_b_q33_7="LifestyleChange-Avoiding Social Gatherings (1=yes, NULL=not)" 
cv19_b_q33_8="LifestyleChange-Not Attending Class (1=yes, NULL=not)" 
cv19_b_q33_9="LifestyleChange-Avoiding Gym Exercise (1=yes, NULL=not)"
cv19_b_q33_10="LifestyleChange-Avoiding Dr Dentist (1=yes, NULL=not)" 
cv19_b_q33_11="LifestyleChange-Working From Home (1=yes, NULL=not)" 
cv19_b_q33_12="LifestyleChange-Avoiding/Canceling Domestic Travel (1=yes, NULL=not)"
cv19_b_q33_13="LifestyleChange-Avoiding/Canceling International Travel (1=yes, NULL=not)"  
cv19_b_q33_14="LifestyleChange-Stocking Food/Supplies (1=yes, NULL=not)" 
cv19_b_q33_15="LifestyleChange-Other (1=yes, NULL=not)"
cv19_b_q33_15T="LifestyleChange-Other Specify (Participant Written Response)" 
cv19_b_q33_16="LifestyleChange-No Change (1=yes, NULL=not)"  
cv19_b_q33_17="LifestyleChange-Mask Usage (1=yes, NULL=not)"
cv19_b_q34="Stay At Home Extent (1=All the time, 2=Most of time, 3=Some of time , 4=none of time)" 
cv19_b_q35="Times Left House in Last 7 Days (Participant Written Response)" 
cv19_b_q36="Why Left House-MultiSelectQx (Select all that apply)"
cv19_b_q36_1="WhyLeftHouse-Work (1=yes, NULL=not)" 
cv19_b_q36_2="WhyLeftHouse-Medical (1=yes, NULL=not)" 
cv19_b_q36_3="WhyLeftHouse-Grocery (1=yes, NULL=not)"
cv19_b_q36_4="WhyLeftHouse-Mail (1=yes, NULL=not)" 
cv19_b_q36_5="WhyLeftHouse-Pet Care (1=yes, NULL=not)"
cv19_b_q36_6="WhyLeftHouse-Outdoor Exercise (1=yes, NULL=not)"
cv19_b_q36_7="WhyLeftHouse-Volunteer (1=yes, NULL=not)" 
cv19_b_q36_8="WhyLeftHouse-Donate Blood (1=yes, NULL=not)" 
cv19_b_q36_9="WhyLeftHouse-Takeout (1=yes, NULL=not)" 
cv19_b_q36_10="WhyLeftHouse-Drugstore (1=yes, NULL=not)" 
cv19_b_q36_11="WhyLeftHouse-Big Box Stores (1=yes, NULL=not)" 
cv19_b_q36_12="WhyLeftHouse-Others House (1=yes, NULL=not)" 
cv19_b_q36_13="WhyLeftHouse-Restaurant/Bar (1=yes, NULL=not)" 
cv19_b_q36_14="WhyLeftHouse-Elderly Care (1=yes, NULL=not)" 
cv19_b_q36_15="WhyLeftHouse-Other (1=yes, NULL=not)" 
cv19_b_q36_15T="WhyLeftHouse-Other Specify (Participant Written Response)" 
cv19_b_q36_16="WhyLeftHouse-Not Left House (1=yes, NULL=not)"
cv19_b_q37="Exposed to COVID-MultiSelectQx (Select all that apply)"
cv19_b_q37_1="ExposedCOVID-Documented Case (1=yes, NULL=not)"
cv19_b_q37_2="ExposedCOVID-Presumed Case (1=yes, NULL=not)"
cv19_b_q37_3="ExposedCOVID-Don't Know (1=yes, NULL=not)" 
cv19_b_q38="Had COVID But Not Tested (1=No, 2=Yes, 3=Not sure)"
cv19_b_q39="Had COVID Symptoms (Y=Yes, N=No, NULL=N/A)"
cv19_b_q40="Days Since Symptoms Started (NULL=N/A)" 
cv19_b_q41="Had COVID Test (Y=yes, N=no)" 
cv19_b_q42="COVID Test Date (MM/DD/YYYY)"
cv19_b_q43="Tested COVID- Positive (1=No, 2=Yes, 3=Waiting)" 
cv19_b_q44="Tested COVID- Last Positive (1=never positive, 2=positive on)" 
cv19_b_q44T="COVID Last Positive Date (MM/DD/YYYY, If Q44=2)" 
cv19_b_q45="Physical Feeling (1=normal, 2=not quite right)"
cv19_b_q46="Have Fever (Y=yes, N=no)" 
cv19_b_q47="Fever Temperature (Participant Written Response)" 
cv19_b_q48="Have Persistent Cough (Y=yes, N=no)" 
cv19_b_q49="Have Unusual Fatigue (N=No, M=Mild, S=Severe)" 
cv19_b_q50="Have Headache (Y=yes, N=no)" 
cv19_b_q51="Have Shortness of Breath (1=No, 2=Yes, Mild, 3=Yes, significant, 4=Yes, Severe)" 
cv19_b_q52="Have Sore Throat (Y=yes, N=no)" 
cv19_b_q53="Have Loss Smell/Taste (Y=yes, N=no)" 
cv19_b_q54="Have Hoarse Voice (Y=yes, N=no)"
cv19_b_q55="Have Chest Pain/Tightness (Y=yes, N=no)" 
cv19_b_q56="Have Abdominal Pain (Y=yes, N=no)" 
cv19_b_q57="Have Diarrhea (Y=yes, N=no)"
cv19_b_q58="Have Nausea (Y=yes, N=no)" 
cv19_b_q59="Skipping Meals (Y=yes, N=no)" 
cv19_b_q60="Other Symptoms (Participant Written Response)" 
cv19_b_q61="Location Right Now (1=home, 2=clinic, symptom, 3=back, tell Rx, 4=back, told Rx)" 
cv19_b_q62="Treatment Right Now 1=none, 2=oxygen & fluids, 3=non-invasive, 4=invasive, 5=other, NULL = N/A)" 
cv19_b_q62T="Treatment Right Now-OtherSpecify (Participant Written Response)"  
cv19_b_q63="Concerned about-Getting COVID (1=not at all, 2=little , 3=moderately, 4=very, 5=extremely)"
cv19_b_q64="Concerned about-Medical Care (1=not at all, 2=little , 3=moderately, 4=very, 5=extremely)" 
cv19_b_q65="Concerned about-Caring For Sick Family (1=not at all, 2=little , 3=moderately, 4=very, 5=extremely)" 
cv19_b_q66="Concerned about-Food/Supplies/Medication (1=not at all, 2=little , 3=moderately, 4=very, 5=extremely)"
cv19_b_q67="Concerned about-Retirement Savings Going Down (1=not at all, 2=little , 3=moderately, 4=very, 5=extremely)" 
cv19_b_q68="Hours of Sleep (1=5 or less, 2=6, 3=7, 4=8, 5=9, 6=10 or more)" 
cv19_b_q69="Have Trouble Sleeping (1=None, 2=less than once a week, 3=1 or 2 times a week, 4=3 or more times a week)"
cv19_b_q70="Rating of Sleep Quality Over Past 2 weeks (1=very good, 2=fairly good, 3=fairly bad, 4=very bad)"
cv19_b_q71="Compared to Before COVID- Sleep Quality over past 2 weeks (1=better, 2=as good, 3=somewhat worse, 4=much worse)" 
cv19_b_q72="Over Last 2 Weeks How Often Bothered by-Feeling Nervous/Anxious/On Edge (1=not at all, 2=several days, 3=more than half the days, 4=Nearly every day)"
cv19_b_q73="Over Last 2 Weeks How Often Bothered by-Worrying (1=not at all, 2=several days, 3=more than half the days, 4=Nearly every day)" 
cv19_b_q74="Over Last 2 Weeks How Often Bothered by-Little Interest/Pleasure in Doing Things (1=not at all, 2=several days, 3=more than half the days, 4=Nearly every day)"
cv19_b_q75="Over Last 2 Weeks How Often Bothered by-Feeling Down/Depressed/Hopeless (1=not at all, 2=several days, 3=more than half the days, 4=Nearly every day)"
cv19_b_q76="Times had Alcohol in Past 2 Weeks (Participant Written Response)" 
cv19_b_q77="Times had 5+ Alcoholic Drinks in Past 2 Weeks (Participant Written Response)" 
cv19_b_q78="Drinking Behavior Change During COVID Pandemic (1=not drink, 2=drink more, 3=drink less, 4=same)" 
cv19_b_q79="Number of People in Household (Participant Written Response)" 
cv19_b_q80="Number of Under Age 18 in Household (Participant Written Response)" 
cv19_b_q81="Number of 65+ in Household (Participant Written Response)"
cv19_b_q82="Number of COVID Positive in Household (Participant Written Response)" 
cv19_b_q83="Number of People w/ COVID Symptoms in Household (Participant Written Response)"  
cv19_b_q84="Household Income Decreased Since COVID Pandemic (1=no, 2=yes, little, 3=yes, lot, 4=don’t know / not sure)"
cv19_b_q85="Provided Financial Support to Family/Friends Due to COVID Pandemic (Y=yes, N=no)" 
cv19_b_q86="Paying For Basic Essentials (1=not hard, 2=somewhat hard, 3=very hard, 4=don’t know / not sure)"
cv19_b_q87="Unable to Pay For Needed Items Since COVID Pandemic (Y=yes, N=no)"
cv19_b_q88="Unable to Pay-MultiSelectQx (Select all that apply)"
cv19_b_q88_1="UnablePay-Food (1=yes, NULL=not)" 
cv19_b_q88_2="UnablePay-Clothing (1=yes, NULL=not)"
cv19_b_q88_3="UnablePay-Utilities (1=yes, NULL=not)"
cv19_b_q88_4="UnablePay-Child Care (1=yes, NULL=not)" 
cv19_b_q88_5="UnablePay-Medicine/Healthcare (1=yes, NULL=not)" 
cv19_b_q88_6="UnablePay-Housing (1=yes, NULL=not)" 
cv19_b_q88_7="UnablePay-Other (1=yes, NULL=not)" 
cv19_b_q88_7T="UnablePay-Other Specify (Participant Written Response)"
cv19_b_q89="Have Healthcare Coverage (Y=yes, N=no, I=I don’t know / not sure)"
cv19_b_q90="Have Primary Care Provider (Y=yes, N=no)" 
cv19_b_q91="Since 3/20/20, Postponed Regular Healthcare Visit Due to COVID Pandemic (Y=yes, N=no)" 
cv19_b_q92="Postpone Provider-MultiSelectQx (Select all that apply)"
cv19_b_q92_1="PostponeProvider-PCP (1=yes, NULL=not)" 
cv19_b_q92_2="PostponeProvider-Oncologist (1=yes, NULL=not)"
cv19_b_q92_3="PostponeProvider-Cardiologist (1=yes, NULL=not)"
cv19_b_q92_4="PostponeProvider-Endocrinologist (1=yes, NULL=not)"
cv19_b_q92_5="PostponeProvider-Other Specialist (1=yes, NULL=not)"
cv19_b_q92_5T="PostponeProvider-OtherSpecialistSpecify (Participant Written Response)"
cv19_b_q92_6="PostponeProvider-Dentist (1=yes, NULL=not)" 
cv19_b_q92_7="PostponeProvider-Other (1=yes, NULL=not)"
cv19_b_q92_7T="PostponeProvider-Other Specify (Participant Written Response)"
cv19_b_q93="Since 3/20/20, Postponed Surgery Due to COVID Pandemic (Y=yes, N=no)"
cv19_b_q94="Postponed Surgery Type (If Q93=Y, Participant Written Response)" 
cv19_b_q95="Since 3/20/20, Postponed Cancer Screening (Y=yes, N=no)" 
cv19_b_q96="Postpone Screening Type- MultiQx (Select all that apply)"
cv19_b_q96_1="PostponeScreeningType-Breast (1=yes, NULL=not)" 
cv19_b_q96_2="PostponeScreeningType-Colerectal Cancer (1=yes, NULL=not)" 
cv19_b_q96_3="PostponeScreeningType-Skin (1=yes, NULL=not)"
cv19_b_q96_4="PostponeScreeningType-Prostate (1=yes, NULL=not)" 
cv19_b_q96_5="PostponeScreeningType-Other (1=yes, NULL=not)" 
cv19_b_q96_5T="PostponeScreeningType-OtherSpecify (Participant Written Response)"
cv19_b_q97="Since 3/20/20, Avoided Getting Urgent Care at ER Due to COVID Pandemic (Y=yes, N=no)" 
cv19_b_q98="Avoided ER-Specify Symptoms Experienced (If Q97=Y, Participant Written Response)"
cv19_b_q99="Cancer Treatment-MultiSelectQx (Select all that apply)"
cv19_b_q99_1="CancerTreatment-None (1=yes, NULL=not)" 
cv19_b_q99_2="CancerTreatment-Chemo (1=yes, NULL=not)" 
cv19_b_q99_3="CancerTreatment-Immuno (1=yes, NULL=not)"
cv19_b_q99_4="CancerTreatment-Radiation (1=yes, NULL=not)"
cv19_b_q100="Since 3/20/20, Postponed Cancer Treatment Due to COVID Pandemic (Y=yes, N=no)" 
cv19_b_q101="Number of Treatment Sessions Canceled (If Q100=Y, Participant Written Response)" 
cv19_b_q102="Willing to Have Blood Test to Detect COVID Antibodies (Y=yes, N=no)" 
cv19_b_q103="Options For Future Testing-MultiSelectQx (If Q102=Y, Select all that apply)" 
cv19_b_q103_1="FutureTesting-At Home (1=yes, NULL=not)"
cv19_b_q103_2="FutureTesting-At Clinic (1=yes, NULL=not)"
cv19_b_q104="Additional Comments (Participant Written Response)";
